### ISSUE TITLE
Support: gmio_stl_mesh_occmesh::init_cache() error when compiling using oce 6.8.0

### ISSUE THREAD

**Issue by Felipeasg** [fougue/gmio#1]
Hi there. After a time working with oce toolkit to read stl I decided to look for something faster and I find gmio, which has a excellent benchmark.

But I have a problem when I try to compile using gcc 4.8.3 and oce 6.8.0.

The problem occurs when the g++ tries compile the gmio_support/stl_occ_mesh.cpp in the function 
gmio_stl_mesh_occmesh::init_cache() (lines  104, 105, 106, 107, 109 and 120)

```
domdata.vec_coords.reserve(seq_vertices.Size());
typedef TColgp_SequenceOfXYZ::const_iterator ConstIterSeqXYZ; 
const ConstIterSeqXYZ seq_end = seq_vertices.cend(); 
for (ConstIterSeqXYZ it = seq_vertices.cbegin(); it != seq_end; ++it) 
      domdata.vec_coords.push_back(&(*it)); 
m_vec_domain_data.push_back(std::move(domdata)); 
```

```
stl_occ_mesh.cpp:104:49: error: within this context domdata.vec_coords.reserve(seq_vertices.Size());

stl_occ_mesh.cpp:106:15: error: 'ConstIterSeqXYZ' does not name a type  const ConstIterSeqXYZ seq_end = seq_vertices.cend();
```

You are using [opencascade 6.8.0 ](https://github.com/tpaviot/oce) from github?

Thanks in advance.

Felipe

**Comment by Felipeasg** [comment]
Some updates.
Chaging the code in **gmio_support/stl_occ_mesh.cpp** above mentioned, by the below:

```
domdata.vec_coords.reserve(seq_vertices.Length());
for(int i = 0; i < seq_vertices.Length(); i++)
    domdata.vec_coords.push_back(new gp_XYZ(seq_vertices.Value(i)));    
m_vec_domain_data.push_back(std::move(domdata));
```

After compiling with flag **-std=c++11**. I can build the code **examples/occstl_read_file.cpp**.

The problem now is when I try use qt_stream to read stl files.
The code is the following:

```
int error = 0;
Handle_StlMesh_Mesh mesh = new StlMesh_Mesh;
gmio_stl_mesh_creator_occmesh mesh_creator(mesh);

QFile fi("/home/saibotgerris/stl_files/sanquer2D_025mm.stl");
fi.open(QIODevice::ReadOnly);

gmio_stream qt_gmio_stream = gmio_stream_qiodevice(&fi);

error = gmio_stl_read(&qt_gmio_stream, &mesh_creator, NULL);
if (error != GMIO_ERROR_OK)
std::cerr << "gmio error: 0x" << std::hex << error << std::endl;
```

The code compiles, but when I run the gmio it return the following error:

**gmio error: 0x7**

In the **gmio_core/error.h** the error is due LC settings (**GMIO_ERROR_BAD_LC_NUMERIC**). Them I changed the slash "/" to double back slash "\\". This work fine. 

But now I have the following error:

**gmio error: 0x11000001**

This seems a error on stl parser... 

I find found the following [site](https://bugreports.qt.io/browse/QTBUG-24444) describing a type of qt bug when read a file is opened with fopen. 
Did you have some similar problem? 
Did you try compile using qt5 and opencascade 6.8.0?

Thanks.

**Comment by Felipeasg** [comment]
I fix this

**Comment by HuguesDelorme** [comment]
@Felipeasg
    Thanks to point the OpenCasacade problem out! Actually previous versions (<7.0.0) of OpenCascade were no checked for compilation, and obviously the "STL" interface for Sequence containers was added recently (maybe in 6.9.0).
    This will be adressed in the next maintenance release of gmio v0.3. 
    Documentation does not mention gmio_support requires C++11, I will try to make gmio_support C++98 compatible (likely in 0.3.1).

For the Qt problems you get :
- As you said, gmio detected that LC_NUMERIC is not set to C or POSIX. This is weird that changing the dir separator to `"\\"` changed also LC_NUMERIC. I would recommend to do the following :

`char old_lcnum[64];`
`strncpy(old_lcnum, setlocale(LC_NUMERIC, NULL), sizeof(old_lcnum));`
`setlocale(LC_NUMERIC, "C");`
`gmio_read_stl(/* ... */);`
`setlocale(old_lcnum);`
LC_NUMERIC is copied because POSIX specifies that the pointer returned by `setlocale()`, not just the
contents of the pointed-to string, may be invalidated by subsequent calls to `setlocale()`.

Though risky, notice you can bypass checking of LC_NUMERIC with [gmio_stl_read_options::stla_dont_check_lc_numeric](http://www.fougue.pro/docs/gmio/0.3/structgmio__stl__read__options.html)
- Error code 0x11000001 maps to GMIO_STL_ERROR_UNKNOWN_FORMAT, and means that gmio failed to guess the format of the STL stream passed in. You should check if the file is correctly opened before proceeding. I think your issue is not related to mixing `QFile` with `FILE*`, because `gmio_stl_read()` uses directly the stream passed in, it does not try to wrap it inside `FILE*` or whatever.
  If you still get that error, feel free to ask more info here. I can also try to test your STL file directly.

**Comment by HuguesDelorme** [comment]
@Felipeasg
I forgot to notice the memory leak about your fix on `gmio_stl_mesh_occmesh`, you should push_back the address returned by `TColgp_SequenceOfXYZ::Value()` instead of doing a new/copy :

`domdata.vec_coords.reserve(seq_vertices.Length());`
`for (int i = 1; i <= seq_vertices.Length(); ++i)`
`    ` `domdata.vec_coords.push_back(&seq_vertices.Value(i));`
`m_vec_domain_data.push_back(std::move(domdata));`

It won't leak and require no extra memory. Notice also that `TColgp_SequenceOfXYZ` index bounds are `1..N` and not `0..N-1`

You might not see a x500 performance boost when writting binary STL, because iteration with the "old" API seems to be less efficient than with "new" STL iterators(introduced in OCC 7.0.0).
It would be interesting to benchmark this ;)

Last but not least, if you have to write ASCII STL, for better performance I would recommend to compile gmio with `-DGMIO_FLOAT2STR_LIB=google_doubleconversion` (or use `cmake-gui`).
For "float-to-string" conversions, this will enable gmio to use the bundled V8's double-conversion C++ library which is faster than the standard C library. For more informations see the [Build instructions](https://github.com/fougue/gmio/wiki/2.-Build-instructions).

**Comment by HuguesDelorme** [comment]
@Felipeasg 
Hello again, some early benchmarks against OpenCascade v6.8.0 (built with VC++ 2013 x64) give these results:

File : [Final_Eiffel_Tower.stl](https://grabcad.com/library/eiffel-tower/files/Final%20Eiffel%20Tower.STL)
Format: Binary STL (little-endian)
Count of triangles: 174762
Size: 8.33MB 

|  | gmio | OpenCascade | ratio |
| --- | --- | --- | --- |
| read | 360ms | 2040ms | 5.67 |
| meshwrite(ascii) | 260ms | 5445ms | 20.94 |
| meshwrite(binary/le) | 12ms | 6501ms | 541.75 |
| meshwrite(binary/be) | 13ms | N/A | N/A |

Writting STL binary is also x500 faster than OpenCascade v6.8.0

**Comment by Felipeasg** [comment]
Thanks by the quick answer...

Well, after try to work with Qt stream without success, I decided try to read a file using the function **gmio_stl_read_file** and the setlocale trick. This work well!!

I think that this is certainly the fastest way to read an stl file and create an opencascade Stl_Mesh.
But I need to find a more efficient way to render the Stl_Mesh using TopoDS_Shape and AIS_Shape. This sill slow yet. 

I changed my code to access the vertex directly to avoid consuming too much memory.

I put an example using oce 6.8.0, gmio and qt5  int the git (https://github.com/Felipeasg/drawSTLShapeGmioOce). If you want I can push it on your example folder.

About the opencascade you are compiling using the 7.0.0 version of (open cascade community edition)[https://github.com/tpaviot/oce] or (occt)[http://git.dev.opencascade.org/gitweb/?p=occt.git] ? because there are some differences between them...

Thanks! Your work help me a lot.

**Comment by HuguesDelorme** [comment]
@Felipeasg 
It's very pleasant to see gmio is useful to you!
I have to check this issue with the Qt stream support in gmio, I will let you know.

For your project, did you consider this solution : after having loaded the StlMesh_Mesh object you could create a `MeshVS_Mesh` object from it.
This is surely faster than creating brep edges and faces for all triangles.
`Handle_MeshVS_Mesh meshVisu = new MeshVS_Mesh;`
`Handle_XSDRAWSTLVRML_DataSource dataSource = new XSDRAWSTLVRML_DataSource(stlMesh);`
`meshVisu->SetDataSource(dataSource);`
`meshVisu->AddBuilder(new MeshVS_MeshPrsBuilder(meshVisu), Standard_True);`
`meshVisu->SetDisplayMode(MeshVS_DMF_Shading);`
`// Display meshVisu in the interactive context`

Another solution would be to define your own functions that builds a custom `MeshVS_DataSource` and let `gmio_stl_mesh_creator` points to these functions.

Last solution would be to define functions for `gmio_stl_mesh_creator` to build a `Poly_Triangulation` that will be owned by an "empty" `TopoDS_Shape` so it can be displayed through `AIS_Shape`.

Notice that next minor version of gmio(v0.4) will support that latter solution(creation of a `Poly_Triangulation`).

I'm using the regular OpenCascade libraries, not OCE.

**Comment by HuguesDelorme** [comment]
Issue fixed in version v0.3.1
